#!/usr/bin/env python3
"""
自动爬取和更新节目源的爬虫程序
支持本地运行和GitHub Actions自动运行
"""

import requests
import os
import subprocess
import time
import sys
from datetime import datetime, timedelta
from pathlib import Path

# 配置
URL = "http://rihou.cc:555/gggg.nzk/"
M3U_FILENAME = "playlist.m3u"
LAST_CHECK_FILE = "last_check.txt"
LOG_FILE = "update.log"

def setup_logging():
    """设置日志记录"""
    import logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(LOG_FILE),
            logging.StreamHandler()
        ]
    )
    return logging.getLogger(__name__)

logger = setup_logging()

def fetch_webpage(url):
    """获取网页内容"""
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1"
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.encoding = response.apparent_encoding
        response.raise_for_status()
        logger.info(f"成功获取网页内容，长度：{len(response.text)}")
        return response.text
    except requests.exceptions.RequestException as e:
        logger.error(f"请求失败：{e}")
        return None

def parse_channels(text):
    """解析频道数据"""
    groups = {}
    current_group = None
    
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        
        # 识别组行（带,且带#genre#）
        if ',' in line and '#genre#' in line:
            parts = line.split(',', 1)
            if len(parts) == 2:
                current_group = parts[0].strip()
                groups[current_group] = []
            continue
        
        # 频道行
        if current_group and ',' in line:
            try:
                channel_name, stream_url = line.split(',', 1)
                channel_name = channel_name.strip()
                stream_url = stream_url.strip()
                
                # 过滤肥羊相关
                if "肥羊" not in channel_name and "肥羊" not in stream_url:
                    groups[current_group].append((channel_name, stream_url))
            except ValueError:
                logger.warning(f"解析行失败：{line}")
                continue
    
    # 移除空组
    groups = {g: chs for g, chs in groups.items() if chs}
    logger.info(f"解析完成，找到 {len(groups)} 个分组，共计 {sum(len(ch) for ch in groups.values())} 个频道")
    return groups

def generate_m3u_content(groups):
    """生成M3U文件内容"""
    content = ['#EXTM3U']
    content.append('# Generated by SelfView Crawler')
    content.append(f'# Update time: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    content.append('')
    
    for group, channels in groups.items():
        if not channels:
            continue
        
        content.append(f'#{group}')
        for channel_name, stream_url in channels:
            content.append(f'#EXTINF:-1 group-title="{group}", {channel_name}')
            content.append(stream_url)
        content.append('')
    
    return '\n'.join(content)

def save_m3u(groups, filename):
    """保存M3U文件"""
    content = generate_m3u_content(groups)
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    # 备份旧文件
    if os.path.exists(filename):
        backup_name = f"{filename}.backup"
        try:
            os.replace(filename, backup_name)
        except:
            pass
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    total = sum(len(ch) for ch in groups.values())
    logger.info(f"写入文件 {filename} 完成，节目总数：{total} 条")

def has_changes(old_content, new_content):
    """检查内容是否有变化"""
    if not old_content:
        return True
    
    # 简单比较（排除注释和时间戳）
    old_lines = [line for line in old_content.splitlines() 
                if not line.startswith('# Generated') and not line.startswith('# Update time')]
    new_lines = [line for line in new_content.splitlines()
                if not line.startswith('# Generated') and not line.startswith('# Update time')]
    
    return old_lines != new_lines

def git_operations():
    """执行Git相关操作"""
    try:
        # 配置Git（仅第一次需要）
        subprocess.run(["git", "config", "--global", "user.email", "actions@github.com"], check=True)
        subprocess.run(["git", "config", "--global", "user.name", "GitHub Actions"], check=True)
        
        # 添加文件
        result = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
        if result.stdout.strip():
            logger.info("检测到文件变化，准备提交")
            subprocess.run(["git", "add", M3U_FILENAME, "update.log"], check=True)
            commit_msg = f"自动更新节目源 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            subprocess.run(["git", "commit", "-m", commit_msg], check=True)
            subprocess.run(["git", "push"], check=True)
            logger.info("Git提交和推送完成")
            return True
        else:
            logger.info("没有检测到文件变化")
            return False
    except subprocess.CalledProcessError as e:
        logger.error(f"Git操作失败：{e}")
        return False

def save_last_check_time():
    """保存最后检查时间"""
    with open(LAST_CHECK_FILE, 'w') as f:
        f.write(datetime.now().isoformat())

def should_run_update():
    """检查是否需要运行更新"""
    if not os.path.exists(LAST_CHECK_FILE):
        return True
    
    try:
        with open(LAST_CHECK_FILE, 'r') as f:
            last_check_str = f.read().strip()
        last_check = datetime.fromisoformat(last_check_str)
        
        # 如果距离上次检查超过7天，则运行更新
        return datetime.now() - last_check > timedelta(days=7)
    except:
        return True

def main():
    """主函数"""
    logger.info("=" * 50)
    logger.info("开始检查节目源更新")
    
    # 检查是否需要更新
    if should_run_update():
        logger.info("距离上次检查已超过7天，开始更新")
    else:
        logger.info("距离上次检查不足7天，跳过更新")
        return
    
    # 读取现有文件内容（用于比较）
    old_content = ""
    if os.path.exists(M3U_FILENAME):
        with open(M3U_FILENAME, 'r', encoding='utf-8') as f:
            old_content = f.read()
    
    # 获取网页内容
    m3u_text = fetch_webpage(URL)
    if not m3u_text:
        logger.error("无法获取节目源，更新失败")
        return
    
    # 解析频道
    groups = parse_channels(m3u_text)
    if not groups:
        logger.error("没有找到有效频道")
        return
    
    # 生成新内容
    new_content = generate_m3u_content(groups)
    
    # 检查是否有变化
    if has_changes(old_content, new_content):
        logger.info("检测到内容变化，更新文件")
        save_m3u(groups, M3U_FILENAME)
        
        # 如果是GitHub Actions环境，执行Git操作
        if os.environ.get('GITHUB_ACTIONS') == 'true':
            git_operations()
        else:
            logger.info("本地运行模式，不执行Git操作")
    else:
        logger.info("内容无变化，无需更新")
    
    # 保存检查时间
    save_last_check_time()
    logger.info("检查完成")

def run_scheduled():
    """定时运行模式（用于本地）"""
    import schedule
    
    logger.info("启动定时检查服务（每周一10:00运行）")
    
    # 每周一10:00运行
    schedule.every().monday.at("10:00").do(main)
    
    # 立即运行一次
    main()
    
    # 保持运行
    while True:
        schedule.run_pending()
        time.sleep(60)

if __name__ == '__main__':
    # 检查命令行参数
    if len(sys.argv) > 1 and sys.argv[1] == '--scheduled':
        run_scheduled()
    else:
        main()
